package hayaa.dataservice.model;

import java.util.Date;

public class RelResourceDataservice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.ID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Integer dataserviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.Status
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_Resource_DataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.ID
     *
     * @return the value of Rel_Resource_DataService.ID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.ID
     *
     * @param id the value for Rel_Resource_DataService.ID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.ResourceID
     *
     * @return the value of Rel_Resource_DataService.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.ResourceID
     *
     * @param resourceid the value for Rel_Resource_DataService.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.DataServiceID
     *
     * @return the value of Rel_Resource_DataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Integer getDataserviceid() {
        return dataserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.DataServiceID
     *
     * @param dataserviceid the value for Rel_Resource_DataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setDataserviceid(Integer dataserviceid) {
        this.dataserviceid = dataserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.Status
     *
     * @return the value of Rel_Resource_DataService.Status
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.Status
     *
     * @param status the value for Rel_Resource_DataService.Status
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.IsDelete
     *
     * @return the value of Rel_Resource_DataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.IsDelete
     *
     * @param isdelete the value for Rel_Resource_DataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_Resource_DataService.CreateTime
     *
     * @return the value of Rel_Resource_DataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_Resource_DataService.CreateTime
     *
     * @param createtime the value for Rel_Resource_DataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:50:09 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}