package hayaa.dataservice.model;

import java.util.Date;

public class RelServerresourceEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.ID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Integer resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.EmployeeID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.Status
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Rel_ServerResource_Employee.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.ID
     *
     * @return the value of Rel_ServerResource_Employee.ID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.ID
     *
     * @param id the value for Rel_ServerResource_Employee.ID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.ResourceID
     *
     * @return the value of Rel_ServerResource_Employee.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.ResourceID
     *
     * @param resourceid the value for Rel_ServerResource_Employee.ResourceID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.EmployeeID
     *
     * @return the value of Rel_ServerResource_Employee.EmployeeID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.EmployeeID
     *
     * @param employeeid the value for Rel_ServerResource_Employee.EmployeeID
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.Status
     *
     * @return the value of Rel_ServerResource_Employee.Status
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.Status
     *
     * @param status the value for Rel_ServerResource_Employee.Status
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.IsDelete
     *
     * @return the value of Rel_ServerResource_Employee.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.IsDelete
     *
     * @param isdelete the value for Rel_ServerResource_Employee.IsDelete
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Rel_ServerResource_Employee.CreateTime
     *
     * @return the value of Rel_ServerResource_Employee.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Rel_ServerResource_Employee.CreateTime
     *
     * @param createtime the value for Rel_ServerResource_Employee.CreateTime
     *
     * @mbg.generated Wed Aug 23 14:45:40 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}