package hayaa.dataservice.model;

import java.util.Date;

public class Sqldataservice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SqlDataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    private Integer dataserviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SqlDataService.DataServiceTitle
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    private String dataservicetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SqlDataService.Status
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SqlDataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    private Boolean isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SqlDataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SqlDataService.DataServiceID
     *
     * @return the value of SqlDataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public Integer getDataserviceid() {
        return dataserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SqlDataService.DataServiceID
     *
     * @param dataserviceid the value for SqlDataService.DataServiceID
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public void setDataserviceid(Integer dataserviceid) {
        this.dataserviceid = dataserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SqlDataService.DataServiceTitle
     *
     * @return the value of SqlDataService.DataServiceTitle
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public String getDataservicetitle() {
        return dataservicetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SqlDataService.DataServiceTitle
     *
     * @param dataservicetitle the value for SqlDataService.DataServiceTitle
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public void setDataservicetitle(String dataservicetitle) {
        this.dataservicetitle = dataservicetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SqlDataService.Status
     *
     * @return the value of SqlDataService.Status
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SqlDataService.Status
     *
     * @param status the value for SqlDataService.Status
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SqlDataService.IsDelete
     *
     * @return the value of SqlDataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SqlDataService.IsDelete
     *
     * @param isdelete the value for SqlDataService.IsDelete
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SqlDataService.CreateTime
     *
     * @return the value of SqlDataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SqlDataService.CreateTime
     *
     * @param createtime the value for SqlDataService.CreateTime
     *
     * @mbg.generated Wed Aug 23 11:05:36 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    private String datascript;
    public  void setDataScript(String value) {
		this.datascript=value;
	}
    public String getDataScript() {
    	return this.datascript;
    }
    private String datamodel;
    public  void setDataModel(String value) {
		this.datamodel=value;
	}
    public String getDataModel() {
    	return this.datamodel;
    }
    private String actionname;
    public  void setActionName(String value) {
		this.actionname=value;
	}
    public String getActionName() {
    	return this.actionname;
    }
    private String databaseconnection;
    public  void setDatabaseConnection(String value) {
		this.databaseconnection=value;
	}
    public String getDatabaseConnection() {
    	return this.databaseconnection;
    }
    private String databaseuser;
    public  void setDatabaseUser(String value) {
		this.databaseuser=value;
	}
    public String getDatabaseUser() {
    	return this.databaseuser;
    }
    private String databasepwd;
    public  void setDatabasePwd(String value) {
		this.databasepwd=value;
	}
    public String getDatabasePwd() {
    	return this.databasepwd;
    }
}